server:
  host: 'localhost'
  port: 3000

db:
  uri: 'localhost:27107'
  dbuser: ''
  dbpass: ''
  db: 'tododb'
  
api:
  prefix: '/api'
  base: 'localhost'

logging:
  console:
    level: debug
    prettyPrint: true
    colorize: true
    silent: false
    timestamp: true
    humanReadableUnhandledException: true
    handleExceptions: true
      