server:
  dev:
    host: 127.0.0.1
    port: 3000
  test:
    host: 127.0.0.1
    port: 3000
  prod:
    host: 127.0.0.1
    port: 3000
    
db:
  dev:
    uri: 'localhost:27107'
    dbuser: ''
    dbpass: ''
    db: 'tododb'
  test:
    uri: 'localhost:27107'
    dbuser: ''
    dbpass: ''
    db: 'tododb'
  prod:
    uri: 'localhost:27107'
    dbuser: ''
    dbpass: ''
    db: 'tododb'

api:
  prefix: '/api'
  base: 'localhost'

logging:
  console:
    level: debug
    prettyPrint: true
    colorize: true
    silent: false
    timestamp: true
    humanReadableUnhandledException: true
    handleExceptions: true
      